apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: acdc
  name: acdc-controller
  labels: {}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: acdc-controller
  template:
    metadata:
      labels:
        app: acdc-controller
        name: acdc-scheduler
        app.kubernetes.io/component: acdc-devops
        app.kubernetes.io/name: acdc-controller
        app.kubernetes.io/part-of: acdc
    spec:
      containers:
        - name: acdc-controller
          image: xdfdotcn/acdc-devops-backend-controller:1.0.0-Alpha-SNAPSHOT
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://meta_db:3306/acdc
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: SERVER_PORT
              value: 8080
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          resources:
            limits:
              cpu: 4000m
              memory: 16Gi
            requests:
              cpu: 4000m
              memory: 16Gi
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
