apiVersion: v1
kind: Service
metadata:
  name: acdc-schema-registry-ui
  namespace: acdc
  labels:
    k8s-app: acdc-schema-registry-ui
spec:
  ports:
    - port: 8000
      protocol: TCP
      name: http
      targetPort: 8000
  selector:
    k8s-app: acdc-schema-registry-ui

