apiVersion: v1
kind: Service
metadata:
  name: acdc-schema-registry
  namespace: acdc
  labels:
    k8s-app: acdc-schema-registry
spec:
  ports:
    - port: 8081
      protocol: TCP
      name: http
      targetPort: 8081
  selector:
    k8s-app: acdc-schema-registry
