# ===================================================================
# Spring Boot configuration .
#
# ===================================================================

logging:
  level:
    ROOT: INFO
    tech.jhipster: INFO
    org.hibernate.SQL: INFO
    cn.xdf.acdc.devops: INFO

spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url:
    username:
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
  liquibase:
    # Remove 'faker' if you do not want the sample data to be loaded automatically
    contexts: dev
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  thymeleaf:
    cache: false

# application:
acdc:
  connector:
    topic:
      schema-history-topic-config:
        partitions: 1
        replication.factor: 1
        cleanup.policy: delete
        retention.ms: 9223372036854775807
        retention.bytes: -1
      server-topic-config:
        partitions: 1
        replication.factor: 1
        cleanup.policy: compact
        compression.type: lz4
